template = "https://github.com/giellalt/template-lang-und"
rev_id = 323
template_sha = "dfd6613f16d25eef74b592360a48496624ab327d"

[replacements]
__GLOTTOLOG_ID__ = "dagb1246"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-dag"
__UND2C__ = "dag"
__UNDEFINED__ = "Dagbani"
__UND__ = "dag"
